# Generated by Django 3.0 on 2020-05-16 21:26

import api.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPXFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('gpx_file', models.FileField(blank=True, upload_to=api.models.gpx_folder, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gpx'])])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GPXTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('elevations', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=13), blank=True, default=list, size=None)),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('gpx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GPXFile')),
            ],
        ),
    ]
