# Generated by Django 3.0 on 2019-12-19 13:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import tracks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gpxFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('gpx_file', models.FileField(blank=True, upload_to=tracks.models.gpx_folder)),
            ],
        ),
        migrations.CreateModel(
            name='GPXTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('gpx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.gpxFile')),
            ],
        ),
        migrations.CreateModel(
            name='GPXPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('gpx_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.gpxFile')),
            ],
        ),
    ]
