# Generated by Django 3.0 on 2020-02-09 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0003_auto_20191221_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrack',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track', to=settings.AUTH_USER_MODEL),
        ),
    ]
