# Generated by Django 3.0 on 2020-02-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_gpxtrack_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpxfile',
            name='title',
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='gpx_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.GPXFile'),
        ),
    ]
