# Generated by Django 3.0 on 2020-02-28 21:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_auto_20200228_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrack',
            name='elevations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=13), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='gpx_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.GPXFile'),
        ),
    ]
