# Generated by Django 3.0 on 2020-02-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20200217_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxfile',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='gpx_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.GPXFile'),
        ),
    ]
