# Generated by Django 3.0 on 2020-02-28 17:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0009_auto_20200224_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrack',
            name='elevations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=5), default=list, size=None),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='gpx_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.GPXFile'),
        ),
    ]
